version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-akory
  php-fpm:
    build:
      context: ./docker/php-fpm
    container_name: php
    depends_on:
      - db
    volumes:
      - .:/var/www/akory
      - /etc/php/8.0/cli/php.ini:/usr/local/etc/php/php.ini
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: '${DATABASE_URL}'
      SYMFONY_ENV: ${APP_ENV}
    networks:
      - app-akory
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "9999:80"
    depends_on:
      -  db
    networks:
      - app-akory
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www/akory
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - app-akory
    ports:
      - "8080:80"

networks:
  app-akory: